#!/bin/bash
#
# Deep Work Session Bootstrap Script
#
# Usage: ./scripts/start_session.sh <project_path>
# Example: ./scripts/start_session.sh projects/demo
#
# This script generates a comprehensive context package for AI agents
# to begin a "Deep Work" session on a specific project.
#

set -e

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check arguments
if [ $# -eq 0 ]; then
    echo -e "${RED}Error: No project path provided${NC}"
    echo "Usage: $0 <project_path>"
    echo "Example: $0 projects/demo"
    exit 1
fi

PROJECT_PATH="$1"
AGENCY_FILE="$PROJECT_PATH/AGENCY.md"

# Validate project path
if [ ! -d "$PROJECT_PATH" ]; then
    echo -e "${RED}Error: Project directory does not exist: $PROJECT_PATH${NC}"
    exit 1
fi

if [ ! -f "$AGENCY_FILE" ]; then
    echo -e "${RED}Error: AGENCY.md not found in $PROJECT_PATH${NC}"
    exit 1
fi

# Get project ID from AGENCY.md
PROJECT_ID=$(grep "project_id:" "$AGENCY_FILE" | head -1 | sed 's/project_id: *//' | tr -d '\r')

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║       AGENT HIVE - DEEP WORK SESSION BOOTSTRAP        ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Project:${NC} $PROJECT_ID"
echo -e "${GREEN}Path:${NC} $PROJECT_PATH"
echo ""

# Generate session context file
SESSION_FILE="$PROJECT_PATH/SESSION_CONTEXT.md"

echo -e "${YELLOW}Generating session context...${NC}"

cat > "$SESSION_FILE" << 'HEADER'
# DEEP WORK SESSION CONTEXT
# Generated by Agent Hive Bootstrap Script

---

## YOUR ROLE

You are an AI agent entering a **Deep Work session** for Agent Hive.

Your mission is to work autonomously on the tasks defined in the AGENCY.md file below.
Before you exit this session, you MUST update the AGENCY.md file to reflect your progress.

### Persona

Adopt the following persona:
- **Name**: Choose a codename for yourself (e.g., "Agent Alpha", "Cortex-7", "DeepMind-42")
- **Specialty**: Identify what you're best at based on the tasks
- **Approach**: Methodical, thorough, and collaborative

### Responsibilities

1. **Read**: Thoroughly understand the AGENCY.md content
2. **Work**: Execute the highest-priority unblocked tasks
3. **Update**: Modify AGENCY.md frontmatter to reflect progress:
   - Set `owner` to your codename while working
   - Mark completed tasks with [x]
   - Update `status` field (active, blocked, completed)
   - Set `blocked: true` with `blocking_reason` if stuck
   - Update `last_updated` timestamp
4. **Document**: Add notes to the "Agent Notes" section with timestamp
5. **Handoff**: Set `owner: null` when done, or keep it if continuing later

---

HEADER

echo "## AGENCY.md CONTENT" >> "$SESSION_FILE"
echo "" >> "$SESSION_FILE"
cat "$AGENCY_FILE" >> "$SESSION_FILE"
echo "" >> "$SESSION_FILE"

echo "---" >> "$SESSION_FILE"
echo "" >> "$SESSION_FILE"
echo "## PROJECT FILE STRUCTURE" >> "$SESSION_FILE"
echo "" >> "$SESSION_FILE"
echo '```' >> "$SESSION_FILE"

# Generate file tree (excluding common ignore patterns)
find "$PROJECT_PATH" -type f \
    ! -path "*/\.*" \
    ! -path "*/__pycache__/*" \
    ! -path "*/node_modules/*" \
    ! -name "*.pyc" \
    ! -name "SESSION_CONTEXT.md" \
    | sed "s|^$PROJECT_PATH|.|" \
    | sort \
    >> "$SESSION_FILE"

echo '```' >> "$SESSION_FILE"
echo "" >> "$SESSION_FILE"

echo "---" >> "$SESSION_FILE"
echo "" >> "$SESSION_FILE"
echo "## GLOBAL CONTEXT" >> "$SESSION_FILE"
echo "" >> "$SESSION_FILE"

# Include GLOBAL.md if it exists
if [ -f "GLOBAL.md" ]; then
    echo "The system-wide context from GLOBAL.md:" >> "$SESSION_FILE"
    echo "" >> "$SESSION_FILE"
    echo '```markdown' >> "$SESSION_FILE"
    head -50 GLOBAL.md >> "$SESSION_FILE"
    echo '```' >> "$SESSION_FILE"
else
    echo "GLOBAL.md not found in repository root." >> "$SESSION_FILE"
fi

echo "" >> "$SESSION_FILE"
echo "---" >> "$SESSION_FILE"
echo "" >> "$SESSION_FILE"

cat >> "$SESSION_FILE" << 'FOOTER'

## HANDOFF PROTOCOL

Before ending your session, complete the following checklist:

- [ ] All completed tasks are marked with [x]
- [ ] Frontmatter field `last_updated` is set to current ISO timestamp
- [ ] Frontmatter field `owner` is set appropriately (your codename or null)
- [ ] Added a timestamped note to "Agent Notes" section
- [ ] If blocked, set `blocked: true` and provided `blocking_reason`
- [ ] Committed any new files created during the session

---

## BOOTSTRAP COMPLETE

**You may now begin your Deep Work session.**

Start by:
1. Analyzing the current state of the project
2. Identifying the highest-priority task you can complete
3. Setting yourself as the `owner` in AGENCY.md frontmatter
4. Working methodically through the tasks

Good luck, agent. 🧠

FOOTER

echo -e "${GREEN}✓ Session context generated: $SESSION_FILE${NC}"
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}NEXT STEPS:${NC}"
echo ""
echo "1. Open $SESSION_FILE"
echo "2. Copy the entire content"
echo "3. Paste it into your AI agent (Claude, Grok, Gemini, etc.)"
echo "4. Let the agent work autonomously"
echo "5. Review the updated AGENCY.md when done"
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}Happy Deep Work! 🚀${NC}"
